import {Html, Head, Main, NextScript} from "next/document"
import { RiSpeakerLine } from "react-icons/ri";

export default function Document() {
  return (
    <Html>
      <Head>
        <meta name="description" content="Tienda de ventas de guitarras y blogs sobre musica" />
        <title>The Guitarists Paradise</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <body>
        <Main/>
        <NextScript/>
      </body>
    </Html>
  )
}
